project:
  type: book
  resources: 
    - "robots.txt" # this file prevents web crawlers from scraping your content for training AI/LLMs.  Downloaded from https://github.com/ai-robots-txt/ai.robots.txt v1.2.0

execute: 
  freeze: auto #only important if your book includes executed code
  
book:
  title: "Fish Population Analysis Lab Handbook"
  search: true
  repo-url: https://github.com/Fish-Population-Analysis-Lab/Modeling-Handbook#
  repo-actions: [edit, issue]
  repo-link-target: "_blank" #makes issue and edit links open in a new window/tab 
  page-footer: 
    left: '© 2024 by El hadji Ndiaye' 
    right: 'Made with [Quarto](https://quarto.org/)'
  author: 
    - name: El hadji Ndiaye
      orcid: 0000-0000-0000-0000
    #add all contributors as additional authors
  date: today #updates date published based on last time it was edited
  chapters:
    - index.qmd #the landing page file *must* be called 'index.qmd'
    - contributing.qmd
    - href: code-of-conduct.qmd
      text: "Code of Conduct" # A different title for the TOC than on the page itself
    - group-expectations.qmd
    - onboarding.qmd
    - offboarding.qmd
    - dashboard-r.qmd
    - research-best-practices.qmd
    - authorship.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    link-external-newwindow: true
    theme: #bootswatch themes.  For other options check out https://bootswatch.com/
      light: flatly
      dark: Cerulean
    css: styles.css
    fonttheme: professionalfonts
aspectratio: 169
fontsize: 11pt

editor: 
  markdown:
    wrap: sentence #Forces each sentence to be on its own line in source markdown, doesn't affect how it is rendered
